---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required software
  apt:
    pkg:
    - apache2
    - php
    - php-mysql
    - default-mysql-client
  become: yes