---

- name: Install required software
  become: true
  apt:
    update_cache: yes
    state: latest
    name:
    - haproxy
  
  
- name: Configure haproxy on layer 7
  become: true
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    block: |
        frontend http_front
           bind 10.10.1.10:80
           default_backend http_back
        backend http_back
           balance roundrobin
           server web1 10.10.1.11:80 check
           server web2 10.10.1.12:80 check
  notify: 
    - restart haproxy