---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install Docker
  shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
  become: yes

- name: Run mysql
  docker_container:
    name: mysql
    image: mysql
    env:
      MYSQL_ROOT_PASSWORD: vagrant
      DB_HOST: 10.10.1.9
      DB_USER: user
      DB_PASSWORD: vagrant
  become: yes