---

- name: Install required software
  become: true
  apt:
    update_cache: yes
    state: latest
    name:
    - mariadb-server
    - python-mysqldb
    - python3-pymysql

- name: Create mysql database
  mysql_db:
    name: 'apache'
    state: present
  become: yes

- name: Create mysql user web
  become: true
  mysql_user:
    name: 'web'
    password: 'vagrant'
    priv: '*.*:ALL,GRANT'
    host: '10.10.1.11'
    state: present

- name: Create mysql user web 2
  mysql_user:
    name: 'web'
    password: 'vagrant'
    priv: '*.*:ALL,GRANT'
    host: '10.10.1.12'
    state: present
  become: yes

- name: Make mysql server listen on all interfaces
  become: true
  blockinfile:
    path: /etc/mysql/my.cnf
    block: |
      [mysqld]
      bind-address = *
  notify: 
    - restart mysql