---

- name: Install git & python3
  become: true
  apt:
    update_cache: yes
    state: latest
    name:
    - git
    - python3-pip

- name: Install setup tools and force upgrade
  pip: 
    name: setuptools
    extra_args: --upgrade

- name: Install hypercorn server
  pip:
    name:
      - hypercorn

- name: Clone FastAPI repo
  git:
    repo: 'https://github.com/manutaitrmn/devops-project-fastapi.git'
    dest: /devops-project-fastapi
    clone: yes
    update: yes

- name: Install specified python requirements
  pip:
    requirements: /devops-project-fastapi/requirements.txt

- name: Run the hypercorn server
  command: hypercorn /devops-project-fastapi/main:app --bind 0.0.0.0:80