---

- name: Install git & python3
  become: true
  apt:
    update_cache: yes
    state: latest
    name:
    - git
    - python3-pip

- name: Install setuptools module and force upgrade
  pip: 
    name: setuptools
    extra_args: --upgrade

- name: Clone FastAPI repo
  git:
    repo: 'https://github.com/manutaitrmn/devops-project-fastapi.git'
    dest: /devops-project-fastapi
    clone: yes
    update: yes

- name: Install specified python requirements
  pip:
    requirements: /devops-project-fastapi/requirements.txt

- name: Run the hypercorn server
  become: true
  shell: hypercorn main:app --bind 0.0.0.0:80 </dev/null >/dev/null 2>&1 &
  args:
    chdir: /devops-project-fastapi/