---

- name: Clone FastAPI repo
  git:
    repo: 'https://github.com/manutaitrmn/devops-project-fastapi.git'
    dest: /
    clone: yes
    update: yes

- name: Install specified python requirements
  pip:
    requirements: /devops-project-fastapi/requirements.txt

- name: Install uvicorn server
  pip:
    name: uvicorn[standard]

- name: Run the uvicorn server
  command: uvicorn /devops-project-fastapi/main:app --host 0.0.0.0 --port 80