---

- name: create docker group
  become: true
  group:
    name: docker
    state: present

- name: add user to group 
  become: true
  user:
    name: "{{ansible_user}}"
    groups: docker
    append: true

- name: install packages required by docker
  become: true
  apt:
    update_cache: yes
    state: latest
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg-agent
    - software-properties-common

- name: add docker GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add docker apt repo
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/debian buster stable
    state: present

- name: install docker
  become: true
  apt:
    update_cache: yes
    state: latest
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io

##### setup ansible <---> docker

- name: Install python dependencies
  become: true
  apt:
    update_cache: yes
    state: latest
    name: python3-pip

- name: install 'Docker SDK for Python'
  pip:
    name: docker

- name: Install git
  become: true
  apt:
    update_cache: yes
    state: latest
    name:
    - git

- name: Clone FastAPI repo
  git:
    repo: 'https://github.com/manutaitrmn/devops-project-fastapi.git'
    dest: /code
    clone: yes
    update: yes

- name: Build the image
  docker_image:
    build:
      path: /code
    name: fastapi-app
    tag: v1
    source: build

- name: Run FastAPI from the generated image
  docker_container:
    name: fastapi
    image: fastapi-app:v1
    ports:
      - "80:80"